### ISSUE TITLE
Dataset open error for datasets collected using multi_d_acquisition_events

### ISSUE THREAD

**Issue by binli123** [micro-manager/pycro-manager#215]
### Bug report

**Bug summary**
I ran into this bug after the latest commit. Datasets collected using multi_d_acquisition_events could not be opened. 
```
~\miniconda3\envs\pmm\lib\site-packages\pycromanager\data.py in __init__(self, dataset_path, full_res_only, remote_storage)
558         if self._remote_storage is None:
559             self._tile_width = (
560                 self.summary_metadata["Width"] - self.summary_metadata["GridPixelOverlapX"]
561             )
KeyError: 'GridPixelOverlapX'
```
It seems that the metadata does not contain 'GridPixelOverlapX' when the tiles are collected using multi_d_acquisition_events  according to a position list.

**Code for reproduction**
```
from pycromanager import Acquisition, Bridge, Dataset, multi_d_acquisition_events
import numpy as np
xy_list = np.zeros((3, 4, 2))
    for x in range(3):
        for y in range(4):
            xy_list[y, x] = [x*512, y*512] # x, y
with Acquisition(save_path, acq_name) as acq:
    events = multi_d_acquisition_events(xy_positions=xy_list.reshape(-1, 2))
    acq.acquire(events)
dataset = Dataset(dataset_path)
```
The KeyError occurs while calling Dataset(save_path).

**Version Info**

  * Operating system: Windows 10
  * pycromanager version: 0.7.8
  * MicroManager version: 20210106
  * Python version: 3.8.5
  * Python environment (command line, IDE, Jupyter notebook, etc): Jupyter notebook

**Comment by henrypinkard** [comment]
Fixed by https://github.com/micro-manager/pycro-manager/pull/216. New version should be on pypi shortly

**Comment by binli123** [comment]
> Fixed by #216. New version should be on pypi shortly

A similar issue still exists after the latest fix. It seems that self.half_overlap is not defined when the XY tiles were collected based on a position list. This happens when try to use dataset.set as_array(stitched=True).
```
dask_array = dataset.as_array(stitched=True)
```
```
~\miniconda3\envs\pmm\lib\site-packages\pycromanager\data.py in recurse_axes(loop_axes, point_axes)
    630                 if axis == "position" and stitched:
    631                     # Stitch tiles acquired in a grid
--> 632                     self.half_overlap = (self.overlap[0] // 2, self.overlap[1] // 2)
    633 
    634                     # get spatial layout of position indices

TypeError: 'NoneType' object is not subscriptable
```

**Comment by henrypinkard** [comment]
What do you mean by position list? using `multi_dimensional_acq_events`? Or using the PosList GUI in MM?

**Comment by binli123** [comment]
> What do you mean by position list? using `multi_dimensional_acq_events`? Or using the PosList GUI in MM?
Using multi_d_acquisition_events with option xy_positions. 
```
with Acquisition(save_path, acq_name) as acq:
    events = multi_d_acquisition_events(xy_positions=position_list.reshape(-1, 2))
    acq.acquire(events)
```

**Comment by henrypinkard** [comment]
Yeah I wouldn't expect that to work. You have to specify the overlap when creating the acquisition to activate tiling mode, and you you have to make sure that your acquisition events have `'row'` and `'col'`. The tiling stuff ignores the actual x and y coordinate, everything is based on these indices. Currently, I dont think theres any way to do row and col with `multi_d_acquisition_events`. Maybe there is an intuitive way to do this -- if you have one in mind feel free to PR
